# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: devops.works tech blog

email: contact@devops.works

description: >- # this means to ignore newlines until "baseurl:"
  Consulting, building & running stacks since @1430344800

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

logo: /images/logo_small_inverted.png
#logo: /images/logo2.png
#twitter_username: jekyllrb
github_username:  devops-works

# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple

search_full_content: true
read_time: true
words_per_minute: 175

plugins:
  - jekyll-feed
  - jekyll-gist

# Footer Links
footer_links:
  - title: Website
    url: https://www.devops.works
    icon: fas fa-link
  - title: GitHub
    url: https://github.com/devops-works
    icon: fab fa-github-square

copyright: "Content &copy; devops.works. You are free to use the stunts depicted in this site at your own risks."

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
